# Generated by Django 3.2.6 on 2024-03-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50)),
                ('airline_name', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.CharField(max_length=50)),
                ('no_of_stops', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchFlightResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_results', models.IntegerField(default=0)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.searchflight')),
            ],
        ),
    ]
