# Generated by Django 3.2.6 on 2024-03-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchflight',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
